- .gitmodules
- add-event.css
- add-event.js
- add.html
Ugly form that works by sending JSON with AJAX.
> Added Add Event page

- add-event.js
Added support for using the ABE backend instance on Heroku
> Enabled Heroku support

- css/app.css
- src/scenes/AddEdit/add-edit-scene.jsx
- src/scenes/AddEdit/save-cancel-buttons.jsx
Finished adding delete and cancel buttons. Still waiting on backend for delete functionality, will remove debug return when ready.
> Single-page app add/edit

- css/app.css
- package-lock.json
- package.json
- src/components/filter-pane.jsx
- src/scenes/Calendar/calendar.jsx
Extracted filtering based on labels from FullCalendar and made a dedicated filter component.
> Filter pane

- css/reactTags.css
- index.html
- package.json
- src/components/tag-entry.jsx
- src/scenes/AddEdit/add-edit-scene.jsx
Currently allows custom tags to be specified, which shouldn't be the case. Will fix later. Likely requires fork of tag component source.
> Implemented React tag selector with autocomplete

- css/app.css
- index.html
- package-lock.json
- src/app.jsx
- src/scenes/Calendar/calendar.jsx
- src/scenes/View/view-event-scene.jsx
Added link on tooltip. Page still needs major UI work.
> Added View Event page

- assets/olin-o-slash.svg
- assets/olin-o.svg
- css/app.css
- src/scenes/AddEdit/location-field.jsx
Should have all the main ones now. Also no longer complains about locations not at Olin (just shows a visual indicator as to whether or not it parsed as an Olin location).
> Added support for more rooms

- app.json
- assets/menu-icon.svg
- public/css/app.css
- src/app.jsx
- src/components/menu-icon-button.jsx
- src/containers/calendar-container.js
- src/containers/sidebar-container.js
- src/data/actions.js
- src/data/reducers.js
- src/scenes/Calendar/calendar.jsx
- src/sidebar/sidebar.jsx
Collapsible on desktop, hidden sidebar (similar to native sidebar menu experience) on mobile.
> Implemented collapsible sidebar

- server.js
- src/app.jsx
- src/components/generate-ics-pane.jsx
- src/components/label-pane.jsx
- src/containers/calendar-container.js
- src/containers/sidebar-container.js
- src/data/actions.js
- src/data/reducers.js
- src/scenes/Calendar/calendar.jsx
- src/sidebar/filter-pane.jsx.js
> Selected/visible labels now encoded in URL for bookmarking and sharing.

- README.md
- index.html.js
- package.json
- server.js
- src/app.jsx
> ABE URL read from environment variable

- src/app.jsx
- src/containers/sidebar-container.js
- src/data/reducers.js
- src/sidebar/sidebar.jsx
Also disabled Redux logger middleware when DEBUG environment variable is set to false or not defined. Closes #82.
> Set sidebar hidden on mobile

- app.json
- index.html
- src/app.jsx
- src/containers/add-edit-container.js
- src/containers/calendar-container.js
- src/containers/import-container.js
- src/containers/view-container.js
- src/data/actions.js
- src/data/reducers.js
- src/scenes/AddEdit/actions-pane.jsx
- src/scenes/AddEdit/add-edit-scene.jsx
- src/scenes/Calendar/calendar.jsx
- src/scenes/Import/import.jsx
- src/scenes/View/view-event-scene.jsx
- src/sidebar/sidebar.jsx
Page (window/tab) title now changes based on which page the user is viewing.
Closes #78.
> Page title changes based on scene

- package-lock.json
- src/containers/calendar-container.js
- src/data/actions.js
- src/scenes/Calendar/calendar.jsx
Fixed bug where clicking Edit in tooltip on recurring event would load page for editing specific occurrence, not series.
> Tooltip edit for recurring series bug fix

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
* Add Travis badges to the README. These show the dev and master status, and can be clicked to navigate to the branch dashboard.
* Add a [PR template](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/). Reminds contributors to run test and lint.
> Add Travis badge and PR template

- server.js
Print the server port as a URL, so the dev can copy/paste it or (in some terminal programs) click on it.
> Print the server url in clickable form

- .gitignore
- package.json
> Fix #147 webpack doesn't pick up changes to environment variables

- src/__test__/__snapshots__/label-pane.test.js.snap
- src/__test__/label-pane.test.js
> Made label pane testings more useful with Oliver

- .eslintrc.yml
- app.json
- index.html.js
- package.json
- public/index.html
- src/sidebar/footer.jsx
* Increase the eslintrc line length to match the source. Makes editor reformatting plugins work.
* Load CSS before js.  Fixes Flash of Unstyled Content
* Update remaining abe-web-front -> abe-web, for name of repo
> Misc. improvements

- src/app.jsx
- src/containers/add-edit-container.js
- src/containers/calendar-container.js
- src/containers/event-details-container.js
- src/containers/sidebar-container.js
- src/data/actions.js
- src/data/reducers.js
- src/data/setup-store.js
- src/pages/add-edit/add-edit-page.jsx
- src/pages/add-edit/recurrence-selector.jsx
- src/pages/details/event-details-page.jsx
- src/sidebar/event-actions-pane.jsx
- webpack.config.js
Connected the event add/edit with the Redux store to avoid making unnecessary server requests. The add/edit page copies the event data to its own state and then modifies it.
Closes #100.
> Integrated add/edit page with Redux

- src/pages/add-edit/add-edit-page.jsx
Added a check to prevent an event from being saved without any labels. Resolves #109.
> No more label-less events

- src/pages/subscription/subscription.jsx
- src/sidebar/generate-ics-pane.jsx
Resolves olinlibrary/abe-web#64
Describe your changes here.
> Updated UX for subscribing in Outlook or Google Calendar

- src/app.jsx
Fixed calendar disappearing when selecting None from label filter Resolves #167.
> Fixed calendar component disappearing

- src/pages/add-edit/add-edit-page.jsx
- src/pages/add-edit/location-field.jsx
- yarn.lock
This resolves #95 by setting the seconds on event start and end times to 0. It also resolves an (undocumented) issue whereby the location field would not recognize Olin locations.
> Time and location bugfixes on add/edit

- public/css/app.css
- src/containers/calendar-container.js
- src/data/actions.js
- src/data/reducers.js
- src/pages/calendar/calendar-page.jsx
- yarn.lock
* Updates URC to fix week view bug and improve UI when displaying lots of events
* Updates usage of URC to match new usage parameters
* Fixes bug where events with same labels don't always show up as same color
* Added event data refresh upon saving event (resolves #156)
> Calendar view fixes

- src/containers/calendar-container.js
- src/data/actions.js
- src/data/setup-store.js
- src/pages/calendar/calendar-page.jsx
Fixed:
* Clicking Today button in week view set first day to today rather than the Sunday of this week
* Clicking Week button showed next week rather than the current one
Also changed the start time of the multi-day views to 8am (so final events aren't cut off) and made this a configurable option via a server environment variable (temporary solution).
> Minor UI fixes

- public/css/app.css
- src/sidebar/footer.jsx
Shrunk elements down a bit to look more reasonable in a non-4K  + Linux environment (which makes everything look tiny).
> Better UI sizing

- public/css/app.css
- src/__test__/__snapshots__/label-pane.test.jsx.snap
- src/components/label-pane.jsx
This is not perfect, but it is better.
Describe your changes here.
> Fix some issues around labels

- src/sidebar/generate-ics-pane.jsx
Resolves #222
Describe your changes here.
> Made subscription button disappear when subscription is generated.

- src/sidebar/generate-ics-pane.jsx
Make subscription button disappear when subscription is generated
> Make subscription button disappear when subscription is generated

- .eslintrc.yml
- src/__test__/label-pane.test.jsx
- src/components/date-time-selector.jsx
- src/components/material-button.jsx
- src/components/menu-icon-button.jsx
- src/components/sidebar-header.jsx
- src/pages/add-edit/add-edit-page.jsx
- src/sidebar/generate-ics-pane.jsx
- src/sidebar/link-pane.jsx
> Daily dose of eslint fixes

- src/__test__/recurrence-selector.test.jsx
- src/docs.js
- src/pages/subscription/subscription.jsx
- src/sidebar/generate-ics-pane.jsx
Open Google Subscribe instructions in new tab.
Link to #wiki-wrapper section of the page.
> Refactor help URLs, and open in new tab

- src/__test__/encoding.test.jsx
- src/__test__/event_details-page.test.jsx
- src/__test__/setup.js
Mock moment to moment-timezone, so tests pass on CI.
> Tests globally mock moment

- src/data/auth.js
- src/sidebar/footer.jsx
- src/sidebar/sidebar.jsx
This is mostly to faciltate testing.
> Add a Sign Out link

- .eslintrc.yml
- public/css/app.css
- src/__test__/__snapshots__/add-edit-page.test.jsx.snap
- src/__test__/__snapshots__/event-details-page.test.jsx.snap
- src/__test__/__snapshots__/label-pane.test.jsx.snap
- src/__test__/add-edit-page.test.jsx
- src/__test__/auth.test.js
- src/__test__/calendar-container.test.js
- src/__test__/event-details-page.test.jsx
- src/__test__/label-pane.test.jsx
- src/__test__/setup.js
- src/components/label-pane.jsx
- src/containers/add-edit-container.js
- src/containers/calendar-container.js
- src/pages/add-edit/add-edit-page.jsx
- src/pages/add-edit/location-field.jsx
- src/pages/details/event-details-page.jsx
- src/sidebar/sidebar.jsx
UI reflects that only admins can apply protected labels and edit protected events
> Protected events

- README.md
- app.json
- docs/CONTRIBUTING.md
- package.json
- src/data/encoding.js
- src/docs.js
- src/sidebar/footer.jsx
- src/sidebar/markdown-guide.jsx
* Update GitHub repo URLs
* Fix an error in the Markdown guide
* Move webpack build from post install to heroku-postbuild
* Remove test:* scripts
> Update repo URLS
