olin-build/abe-web

- public/css/app.css
- src/scenes/AddEdit/location-field.jsx
Building, room, suffix boxes hidden until an Olin location is recognized. Needs a better thought-out solution long-term. Also added the CC Crescent Room as a recognized location.
> Location field UI patch to avoid some confusion

- src/scenes/AddEdit/add-edit-scene.jsx
Fixed bug where unchecking recurrence checkbox wouldn't remove recurrence data from event. Closes #98.
> Fix for not being able to disable recurrence of an event

- .env.template
- .gitignore
- README.md
- package.json
README:
* Add brew instructions for macOS
* Default instructions now work with local instance of ABE back end
package.json:
* Upgrade to node 9.x, so that out-of-box instructions work with current node download
.gitignore:
* Add a couple of files created by `yarn webpack:deploy`
> Update README; remove

- README.md
- webpack.config.js
This modifies the webpack devserver config to serve from http://localhost/ instead of http://localhost/public/. This fixes an issue that (despite the README) has been a source of confusion; brings the actual instructions into line with those that webpack prints to the console when it starts; and also fixes the issue that when the app is run from /, the developer must then click on the icon to get to the actual calendar view.
> Fix #106 modify dev build to serve from / instead of /public

- README.md
- package.json
- src/__test__/__snapshots__/label-pane.test.js.snap
- src/__test__/label-pane.test.js
- yarn.lock
This change adds `yarn test` and `yarn test:watch` to run Jest tests. (`test:watch` runs in *watch* mode: the test runner never exits, and it re-runs when a file changes. This way you can keep it running in one window or pane while you edit code in another.)
There’s sample tests for the `LabelPane` component. These are [snapshot tests](https://facebook.github.io/jest/docs/en/snapshot-testing.html): the first run saves a snapshot of the generated DOM hierarchy, as JSON, in a file; subsequent runs verify that the code generates the same DOM. If the tests are comprehensive, this gives you a high degree of confidence in re-factoring the implementation without introducing regressions. Jest also supports more conventional expectation- and assertion-based testing.
The tests are just a beginning …
> Add jest for testing, and first test

- index.html
- index.html.js
- src/app.jsx
- webpack.config.js
Use `webpack.EnvironmentPlugin` to expose build-time environment
variables (`ABE_URL`, `DEBUG`, `GA_ID`) as runtime `process.env[*]`.
This is a hotfix to `master`, to work around the outage caused by  olinlibrary/ABE#143. It makes minimal changes. I'm preparing a different PR based on this one, but with additional simplifications, to apply to `dev`. That will also be an increment towards #125.
> Fix #124 Production isn't picking up changes to ABE_URL

- README.md
- index.html.js
- public/index.html
- server.js
- src/app.jsx
- webpack.config.js
This is the dev version of the production hotfix PR #126 (that fixes #124). It additional updates the default `ABE_URL` and README such that the app can run against the a local ABE back end with no configuration; and removes the use of `window` as an intermediary for storing `DEBUG` and `GA_ID`.
Future work, that is enabled by these changes but that this PR doesn't implement, is:
* Server a static `index.html`.
* Use a provider pattern to provide the value of `ABE_URL`, instead of storing it on `window`.
> Use webpack environment plugin to access ABE_URL (dev version)

- .editorconfig
- .eslintrc.yml
- .travis.yml
- README.md
- package.json
- yarn.lock
Add a Travis configuration file. The current CI status is [here](https://travis-ci.org/olinlibrary/abe-web); you can also see that Travis has annotated this PR status.
Add a `yarn lint` script, that uses [ESLint](https://eslint.org).
Add an [EditorConfig](http://editorconfig.org/) file.
> Add CI and lint

- server.js
- src/app.jsx
- src/containers/subscription-container.js
- src/pages/subscription/subscription.jsx
- src/sidebar/generate-ics-pane.jsx
In order to support the security requirements of the system, as well as to allow the user to edit which labels they can see on a given subscription after they create it, this PR changes the way that subscriptions are handled to ask the server for a unique ID. It also adds a page to enable editing of which labels those subscriptions pull from.
The backend currently supports all of the endpoints needed to make this work, but the data is not yet being stored in the database, so it might be worth holding off until that is implemented before merging this to master.
> New creation and editing workflow for subscriptions

- src/__test__/label-pane.test.js
- src/components/label-pane.jsx
Take advantage of the fact that label-pane has test cases to refactor it some; also incorporate into its API some learnings from trying to figure out how to use it while writing tests.
Specifically, `contentClass`, `general`, and `selectedLabels` now have defaults. This simplifies the test cases some.
> Add default properties to <label-pane>

- public/css/app.css
- src/__test__/__snapshots__/label-pane.test.js.snap
- src/components/label-pane.jsx
In consultation with Jeff:
* Added the closest matching icon from the Ionic framework.
* Unselected tags use the tag color
* [Roundrects](https://www.folklore.org/StoryView.py?story=Round_Rects_Are_Everywhere.txt)!
* [n/a] New code is covered by new or existing tests.
> Re-style tag clouds

- .eslintrc.yml
- README.md
- package.json
- server.js
- src/__test__/label-pane.test.js
- src/components/plain-english-recurrence.jsx
- webpack.config.js
Enable the [comma-dangle](https://eslint.org/docs/rules/comma-dangle.html) eslint rule.
Add `yarn format` to fix eslint issues.
Fix a handful of comma-dangle issues.
Note: a couple of concessions are made, in order to prevent a large number of changes that woud likely cause merge conflicts with outstanding branches:
1. comma-dangle is a warning, not an error
2. files in src aren't fixed
> Add trailing commas to multi-line objects and arrays

- src/pages/add-edit/add-edit-page.jsx
`AddEditEventPage.validateInput()` was ignoring the rest of the tests if the title was non-empty.
This would be a great spot to add tests, but I foundered on `import MenuIconSVG from 'svg-react-loader?name=Icon!../../assets/menu-icon.svg';` in `menu-icon-button.jsx` not working in Jest, and timed out on workarounds / solutions.
Instead, I tested some of the cases manually.
> Invalid events weren't showing alerts

- package.json
- yarn.lock
a862c48 *Remove isomorphic-fetch@latest from deps*
This conflicted with isomorphic-fetch@2.2.1, hoisted from flux#fbjs#isomorphic-fetch, and was skipped with a warning:
```
warning Pattern ["isomorphic-fetch@latest"] is trying to unpack in the same destination "/Users/osteele/Library/Caches/Yarn/v1/npm-isomorphic-fetch-2.2.1-611ae1acf14f5e81f729507472819fe9733558a9" as pattern ["isomorphic-fetch@^2.1.1"]. This could result in non-deterministic behavior, skipping.
```
e7a3449 *Add dep on commonmark-react-renderer@4.3.4*
Fixes a peer dependency warning
```
warning " > commonmark-react-renderer@4.3.4" has unmet peer dependency "commonmark@^0.27.0 || ^0.26.0 || ^0.24.0".
```
991841e *Move a couple packages from devDepencies to dependencies*
Tested via `yarn install --production && yarn …
> Package dependencies

- .eslintrc.yml
- src/containers/sidebar-container.js
- src/pages/add-edit/add-edit-page.jsx
- src/pages/calendar/calendar-page.jsx
- src/pages/details/event-details-page.jsx
- src/pages/import/import.jsx
- src/pages/subscription/subscription.jsx
- src/sidebar/filter-pane.jsx
- src/sidebar/sidebar.jsx
Remove the exemption for eslint import/extensions rule (from Airbnb), and fix the sources.
* [n/a] New code is covered by new or existing tests.
* [n/a] Changed code is covered by new or existing tests.
> Remove exemption for eslint import/extensions rule

- .eslintrc.yml
- package.json
- src/containers/calendar-container.js
- src/containers/import-container.js
- src/containers/sidebar-container.js
- src/containers/subscription-container.js
- src/data/setup-store.js
- src/pages/calendar/calendar-page.jsx
80d9ee5 *Fix a lint error*
Also `initialState` was initialized from `window.debug` instead of `process.env.DEBUG`.
bf90c26 *Disable a11y warnings*
#118 represents these; they don't need to clutter up the log until we're ready to tackle them.
fd07565 *Teach eslint about __REDUX_DEVTOOLS_EXTENSION_COMPOSE__*
28efe3a *Obey eslint import/first rule*
03a6085 *Add prop-types to package.json.dev*
Per https://reactjs.org/blog/2017/04/07/react-v15.5.0.html
Eliminates a number of eslint warnings:
```
warning  'prop-types' should be listed in the project's dependencies. Run 'npm i -S prop-types' to add it  import/no-extraneous-dependencies
```
* [n/a] New code is covered by new or existing tests.
* …
> Chip away at eslint

- .eslintrc.yml
- package.json
- src/pages/add-edit/add-edit-page.jsx
- yarn.lock
Fixed loading and editing recurring series and single recurrence data. Full testing unfortunately blocked by https://github.com/olinlibrary/ABE/issues/210. Also fixed some indentation issues. 
> Fixed editing recurrences

- src/containers/add-edit-container.js
- src/containers/event-details-container.js
- src/containers/sidebar-container.js
- src/pages/add-edit/add-edit-page.jsx
- src/pages/details/event-details-page.jsx
* Stopped `color` from being sent to server on event save (caused 500 response)
* Fixed issue toggling labels
* Fixed current event data not being cleared when navigating between pages not using the sidebar home button
> More add/edit page fixes

- .eslintrc.yml
- src/__test__/add-edit-page.test.jsx
- src/app.jsx
- src/containers/labels-container.js
- src/data/actions.js
- src/data/sidebar-modes.js
- src/pages/labels/labels.jsx
- webpack.config.js
51257e2 *Add a Labels page, for admins to review labels*
Adds a  Labels page, at `/labels`. This page makes it easier for an administrator to review the labels, their descriptions, colors, and flags.
This page isn't part of the public UI. It's not protected by auth, since it doesn't (yet) allow modifications to the set of labels, but there's no link to it.
f0b01a5 *Change eslint indent from indent to warn*
This turns out to be the easiest way to get editors that respect eslint settings to respect this project's 2-char indentation convention.
30fc4ec *Apply 2-char indentation to a couple of files*
0de0ba3 *Labels page sets sidebar and title*
* [☹️] New code is covered by new or existing …
> Add a Labels page, for admins to review labels

- src/data/actions.js
- src/pages/calendar/calendar-page.jsx
Fixed:
* Event deletion not reflected on calendar until page refresh
* Labels not loaded from URL anymore
> UX bugfixes: refresh on delete & load labels from URL

- src/__test__/__snapshots__/label-pane.test.jsx.snap
- src/__test__/add-edit-page.test.jsx
- src/__test__/label-pane.test.jsx
- src/components/label-pane.jsx
Sort labels. Currently “featured” goes first, then default labels, then non-defaults, with labels alphabetized within each section. This feels right for the sidebar 
This also fixes an issue where “Final Events” displayed funny in the Add/Edit Event view, because its name (with an unquoted space) was used as a CSS selector. Now the label id is used.
Also expected the Object and Array proptypes to specify their values.
> Sort labels

- .travis.yml
- README.md
- package.json
- yarn.lock
Sends code coverage to coveralls.io. Examples:
* [This PR's coverage report](https://coveralls.io/github/olinlibrary/abe-web)
* [`add-edit-page.jsx`'s coverage annotation](https://coveralls.io/builds/16895738/source?filename=src%2Fpages%2Fadd-edit%2Fadd-edit-page.jsx)
Adds a badge to the README.
Completes #144.
> Report test coverage to coveralls.io

- package.json
- src/__test__/__snapshots__/event_details-page.test.jsx.snap
- src/__test__/encoding.test.jsx
- src/__test__/event_details-page.test.jsx
- src/data/actions.js
- src/data/encoding.js
- src/pages/add-edit/add-edit-page.jsx
- src/pages/details/event-details-page.jsx
- yarn.lock
09dbd6f *Replace allDay -> all_day in server API*
Starts #214
This allows the client to work with old- and new-API servers. Once the client is deployed through to production, and then the API server is deployed through to production and on dev branches, then the API version detection can be backed out.
0e2a206 *Fixes #212 all-day events have end time, other events don't*
Verified by manual inspection of the snapshot file. Now that this is done, the test should prevent regressions.
> Fix the time display of all day (and non-all-day) events, and handle all_day property

- src/containers/sidebar-container.js
- src/data/reducers.js
- src/data/setup-store.js
- src/sidebar/sidebar.jsx
Start #217, #179.
Remaining work depends on olinlibrary/ABE#214. This work is to retrieve the account info from `GET /account` instead of initializing it to a constant that grants all permissions; to extend `withServerInfo` (currently in PR #219) to verify that the account has been loaded; and to guard the Sidebar by `withServerInfo`.
> Hide unauthorized ui

- .eslintrc.yml
- src/components/date-time-selector.jsx
- src/components/picker-popup.jsx
- src/pages/add-edit/add-edit-page.jsx
- src/pages/add-edit/save-cancel-buttons.jsx
- src/sidebar/event-actions-pane.jsx
- src/sidebar/footer.jsx
- src/sidebar/markdown-guide.jsx
Incremental eslint-airbnb compliance.
> Daily eslint

- src/app.jsx
- src/containers/calendar-container.js
- src/containers/sidebar-container.js
- src/containers/with-server-data.jsx
- src/data/actions.js
- src/data/reducers.js
- src/data/setup-store.js
- src/sidebar/sidebar.jsx
The client fetches account info from the server, and uses this to
control the presentation of elements that require auth.
> Completes #54, #175, #179 #217

- src/__test__/auth.test.js
- src/app.jsx
- src/data/actions.js
- src/data/auth.js
- src/sidebar/sidebar.jsx
When the user is outside the network, offer an option to sign in via OAuth. Save the access token in local storage for use in a subsequent session; and present it as a bearer token on API requests.
> Enable OAuth sign-in

- public/css/app.css
- src/__test__/add-edit-page.test.jsx
- src/app.jsx
- src/containers/import-container.js
- src/containers/subscription-container.js
- src/data/actions.js
- src/data/client.js
- src/data/reducers.js
- src/data/setup-store.js
- src/pages/add-edit/add-edit-page.jsx
- src/pages/import/import.jsx
- src/pages/subscription/subscription.jsx
- src/sidebar/generate-ics-pane.jsx
- src/sidebar/sidebar.jsx
* Replace (most) use of base `axios` methods by calls on an axios instance that knows the API server's base URL
* (wip) Add a message list, as a future alternative to `alert`.
> Factor out client API; show some messages in the page
